default_metadata = {'electrode_group': {'description': "'NA'", 'location': "'NA'", 'name': "'NA'"},
 'electrode_metadata': [{'filtering': "'None'",
                         'id': '1',
                         'impedance': '1',
                         'location': "'NA'",
                         'x': '1',
                         'y': '2',
                         'z': '3'}],
 'file_electrodes': {},
 'session': {'description': "'NA'",
             'device_name': "'NA'",
             'start_time': "'31-Jul-2021 180230'"}}